name: Build quickjs

on: 
  push:

jobs:
#  build_ubuntu:
#    name: Ubuntu 
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Checkout quickjs
#      uses: actions/checkout@v2
#      with:
#        repository: 'bellard/quickjs'
#        path: ${{github.workspace}}/quickjs/
#    - name: Run build script
#      run: |
#        cd $GITHUB_WORKSPACE
#        cp -r qjs-build/* $GITHUB_WORKSPACE/quickjs/
#        cd $GITHUB_WORKSPACE/quickjs/
#        sh make_linux64.sh
#    - uses: actions/upload-artifact@v2
#      with:
#        name: qjs_bin
#        path: ~/qjs/**/*
#        
#  build_macos:
#    name: macOS
#    runs-on: macos-10.15
#    steps:
#    - uses: actions/checkout@v2
#    - name: Checkout quickjs
#      uses: actions/checkout@v2
#      with:
#        repository: 'bellard/quickjs'
#        path: ${{github.workspace}}/quickjs/
#    - name: Run build script
#      run: |
#        cd $GITHUB_WORKSPACE
#        cp -r qjs-build/* $GITHUB_WORKSPACE/quickjs/
#        cd $GITHUB_WORKSPACE/quickjs/
#        sh make_osx.sh
#    - uses: actions/upload-artifact@v2
#      with:
#        name: qjs_bin
#        path: ~/qjs/**/*
#        
#  build_ios:
#    name: iOS
#    runs-on: macos-10.15
#    steps:
#    - uses: actions/checkout@v2
#    - name: Checkout quickjs
#      uses: actions/checkout@v2
#      with:
#        repository: 'bellard/quickjs'
#        path: ${{github.workspace}}/quickjs/
#    - name: Run build script
#      run: |
#        cd $GITHUB_WORKSPACE
#        cp -r qjs-build/* $GITHUB_WORKSPACE/quickjs/
#        cd $GITHUB_WORKSPACE/quickjs/
#        sh make_ios.sh
#    - uses: actions/upload-artifact@v2
#      with:
#        name: qjs_bin
#        path: ~/qjs/**/*
        
  build_window:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Checkout quickjs
      uses: actions/checkout@v2
      with:
        repository: 'bellard/quickjs'
        path: ${{github.workspace}}/quickjs/
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'cmake mingw-w64-x86_64-toolchain'
    - name: Run build script
      run: |
        msys2 -c 'cmake --version'
        msys2 -c 'cp -r qjs-build/* quickjs/'
        cd quickjs
        msys2 -c 'sh make_msys2.sh'
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_bin
        path: ~/qjs/**/*


